# Generated by Django 6.0.2 on 2026-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='course_master',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='photodata',
            fields=[
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='st_course',
            fields=[
                ('st_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('commencement_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='st_installment',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('t_date', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
